// ============================================================
//  MEAL REFERENCE DATA — GOD MODE UPDATE (May 2026)
//  All Shopify product names verified + station assignments synced
//  with Gemini God Mode engine
// ============================================================

// Direct to Assembly items — bypass all hot line stations
// Print exact unit count instead of batches
const DIRECT_TO_ASSEMBLY = [
  "Meatball Parmesan Wrap",
  "Vegan Breakfast Sandwich"
];

const GROUP1_MEALS = [

  {
    name: "Baja Chicken Tacos",
    yield: 75,
    baselineRate: 176,
    stove: "",
    oven: "",
    grill: "Baja Chicken",
    flatGrill: "",
    saladStation: "Cut Cilantro",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Basmati Rice',
    rawMeats: "Filet Chicken",
  },

  {
    name: "Baked Herbed Tilapia (1lb Competition Approved)",
    yield: 6,
    baselineRate: 14,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Tilapia',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "BBQ Chicken Garlic Parm Potatoes",
    yield: 79,
    baselineRate: 245,
    stove: "BBQ Chicken Garlic Parm Potatoes Sauce",
    oven: "",
    grill: "",
    flatGrill: "BBQ Garlic Parm Chicken",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Cube Potatoes',
    holbrook: '',
    rawMeats: "Cube Chicken",
  },
  {
    name: "Blueberry French Toast",
    yield: 65,
    baselineRate: 66,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Blueberry Frenchie",
    saladStation: "",
    sauceStation: "Blueberry French Toast Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Brookfield Chicken Bowl",
    yield: 90,
    baselineRate: 154,
    stove: "Cilantro Lime Rice",
    oven: "Brookfield Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Broritto Burrito",
    yield: 75,
    baselineRate: 277,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Burrito Salad",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Chipotle Chicken',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Buffalo Chicken Meatballs",
    yield: 120,
    baselineRate: 119,
    stove: "",
    oven: "Buffalo Chicken Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Buffalo Meatball Sauce",
    mainKitchen: 'Sweet Potato Fries',
    holbrook: '',
    rawMeats: "Ground Chicken",
  },
  {
    name: "Buffalo Crispy Chicken Wrap",
    yield: 85,
    baselineRate: 189,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Celery",
    sauceStation: "Buffalo Crispy Chicken Sauce",
    mainKitchen: 'Mix Buffalo Crispy, Buffalo Crispy Chicken',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Chicken Mushroom Pot Stickers",
    yield: 77,
    baselineRate: 63,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Sliced Mushrooms",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },


  {
    name: "Cinnamon Roll Pancakes",
    yield: 60,
    baselineRate: 61,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Cinnamon Roll Pancakes",
    saladStation: "",
    sauceStation: "Cinnamon Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Club Wrap",
    yield: 73,
    baselineRate: 96,
    stove: "",
    oven: "Club Wrap Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Club Wrap Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Pesto Chicken",
  },
  {
    name: "Competition Approved Chicken Kebab (1lb)",
    yield: 28,
    baselineRate: 42,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Chicken Kebab',
    holbrook: '',
    rawMeats: "Cube Chicken",
  },
  {
    name: "Competition Approved Grilled Chicken (1lb)",
    yield: 25,
    baselineRate: 109,
    stove: "",
    oven: "",
    grill: "Arnold Chicken",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Competition Approved Sticky Rice (1lb)",
    yield: 32,
    baselineRate: 40,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Sticky Rice',
    rawMeats: "",
  },
  {
    name: "Competition Approved Oven Baked Cod (1lb)",
    yield: 5,
    baselineRate: 13,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Cod',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Crispy Vegan Wrap",
    isVegan: true,
    yield: 48,
    stove: "",
    oven: "Vegan Crispy Tenders",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Vegan Crispy Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Farfalle & Chicken Alfredo",
    yield: 85,
    baselineRate: 122,
    stove: "Farfalle Pasta & Sauce",
    oven: "Farfalle Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Scallions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Fit Ala Vodka With Chicken",
    yield: 85,
    baselineRate: 126,
    stove: "Penne Vodka Sauce",
    oven: "",
    grill: "Basil Chicken",
    flatGrill: "",
    saladStation: "Parsley",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Fit-Fil-A",
    yield: 75,
    baselineRate: 104,
    stove: "",
    oven: "Smoked Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Fit Fil-A Waffle Fries',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "GLORIOUS GAINS Steak Bites & Cilantro Lime Rice",
    yield: 70,
    baselineRate: 141,
    stove: "Cilantro Lime Rice",
    oven: "",
    grill: "",
    flatGrill: "Glorious Steak",
    saladStation: "",
    sauceStation: "Glorious Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Cube Steak",
  },
  {
    name: "Gluten Free Carbonara Chicken",
    yield: 79,
    baselineRate: 98,
    stove: "GF Pasta & Sauce",
    oven: "",
    grill: "Carbonara Chicken",
    flatGrill: "",
    saladStation: "Parsley",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },

  {
    name: "Grilled Chicken Pesto Wrap",
    yield: 73,
    baselineRate: 116,
    stove: "",
    oven: "Pesto Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Fresh Mozzarella",
    sauceStation: "Pesto Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Pesto Chicken",
  },
  {
    name: "Hey Arnold! Burrito",
    yield: 75,
    baselineRate: 125,
    stove: "Jasmine Rice",
    oven: "",
    grill: "Hey Arnold Chicken",
    flatGrill: "",
    saladStation: "Hey Arnold Salad",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Hot Honey Steak & Mac",
    yield: 68,
    baselineRate: 102,
    stove: "Rotini Pasta",
    oven: "",
    grill: "Hot Honey Steak",
    flatGrill: "",
    saladStation: "Mix Rotini Pasta",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Meatball Parmesan Wrap",
    yield: 30,
    baselineRate: 113,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },

  {
    name: "Nacho Average Vegan Bowl",
    isVegan: true,
    yield: 28,
    stove: "",
    oven: "Vegan Chorizo",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Sweet Potato Fries',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Soho Steak Bowl",
    yield: 90,
    baselineRate: 112,
    stove: "",
    oven: "",
    grill: "Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Sweet Potato Fries',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Southwest Chicken Bowl",
    yield: 75,
    baselineRate: 147,
    stove: "",
    oven: "SW Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Corn Salad",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Basmati Rice',
    rawMeats: "Filet Chicken",
  },

  {
    name: "Spicy Buffalo Wrap",
    yield: 73,
    baselineRate: 147,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Chicken Kebab',
    holbrook: '',
    rawMeats: "Cube Chicken",
  },
  {
    name: "Stacked and Jacked",
    yield: 103,
    baselineRate: 118,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Burger Patty",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Mix & Form Burgers, Stacked and Jacked Potato',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Strawberry Protein French Toast",
    yield: 65,
    baselineRate: 66,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Strawberry Frenchie",
    saladStation: "",
    sauceStation: "Strawberry French Toast Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Thai Chili Chicken",
    yield: 72,
    baselineRate: 125,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Thai Chili Chicken",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Sticky Rice',
    rawMeats: "Cube Chicken",
  },
  {
    name: "Turkey Bacon Cheddar Egg Muffins",
    yield: 44,
    baselineRate: 38,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Egg Muffin',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Vegan Breakfast Sandwich",
    yield: 1,
    baselineRate: 11,
    directToAssembly: true,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Vegan Cheeseburger Bowl",
    isVegan: true,
    yield: 28,
    stove: "",
    oven: "Vegan Chorizo",
    grill: "",
    flatGrill: "",
    saladStation: "Onion/Pickle",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Basmati Rice',
    rawMeats: "",
  },

  {
    name: "TexMex Potato Hash",
    yield: 84,
    baselineRate: 120,
    stove: "",
    oven: "Texas Potatoes",
    grill: "",
    flatGrill: "",
    saladStation: "Texas Hash Salad",
    sauceStation: "",
    mainKitchen: 'Ground Beef, Cube Potatoes',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Nacho Average Bowl",
    yield: 71,
    baselineRate: 71,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Sweet Potato Fries, Ground Beef',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Southwest Chicken Quesadilla",
    yield: 80,
    baselineRate: 137,
    stove: "Pulled Chicken",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Quesadilla Veggies",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },

  {
    name: "Strongsville Chicken Bacon Ranch Fold",
    yield: 88,
    baselineRate: 138,
    stove: "",
    oven: "Ranch Fold Chicken, Bacon",
    grill: "",
    flatGrill: "",
    saladStation: "Mix Ranch Fold",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken"
  },
  {
    name: "Taco Build Quesadilla",
    yield: 104,
    baselineRate: 100,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Taco Build Chicken",
    saladStation: "Mix Taco Build Quesadilla",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Triple Cut Cube"
  },
  {
    name: "Cheeseburger Bowl",
    yield: 93,
    baselineRate: 124,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Onion/Pickle",
    sauceStation: "",
    mainKitchen: 'Ground Beef',
    holbrook: 'Basmati Rice',
    rawMeats: "",
  },
];

const GROUP2_MEALS = [
  {
    name: "Low Carb Keto Cheeseburger Bowl",
    yield: 80,
    baselineRate: 90,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Onion/Pickle",
    sauceStation: "",
    mainKitchen: 'Ground Beef',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Chicken Taco Bowl",
    yield: 80,
    baselineRate: 117,
    stove: "Brown Rice, Chicken Taco Bowl Chicken",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Red Bean Corn Salad",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },


  {
    name: "6-Guys Patty Melt",
    yield: 102,
    baselineRate: 95,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Burger Patty",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Mix & Form Burgers, Sweet Potato Fries',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "BBQ Meltdown",
    yield: 70,
    baselineRate: 120,
    stove: "Jasmine Rice",
    oven: "",
    grill: "",
    flatGrill: "BBQ Chicken - BBQ Meltdown",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Cube Chicken",
  },
  {
    name: "BBQ Chicken Mac Bowl",
    yield: 80,
    baselineRate: 95,
    stove: "Rotini Pasta",
    oven: "",
    grill: "",
    flatGrill: "Barbecue Chicken",
    saladStation: "Scallions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Cube Chicken"
  },
  {
    name: "Breakfast Burrito",
    yield: 75,
    baselineRate: 108,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Yellow Eggs",
    saladStation: "Cube Red and Green Peppers, Bacon",
    sauceStation: "",
    mainKitchen: 'Frozen Cube Potatoes',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Buffalo Chicken Quesadilla",
    yield: 87,
    baselineRate: 110,
    stove: "Buffalo Quesadilla Chicken",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Buffalo Chicken Quesadilla Veggies",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Buffalo Mac N Chicken",
    yield: 90,
    baselineRate: 106,
    stove: "Elbow Pasta Mix",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Chicken Kebab',
    holbrook: '',
    rawMeats: "Cube Chicken"
  },

  {
    name: "Chicken Stir Fry",
    yield: 80,
    baselineRate: 107,
    stove: "Peas/Carrots Rice",
    oven: "",
    grill: "",
    flatGrill: "Stir Fry Chicken",
    saladStation: "Scallions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Cube Chicken"
  },
  {
    name: "Competition Approved 90/10 Lean Ground Beef (1lb)",
    yield: 22,
    baselineRate: 33,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Ground Beef',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Competition Approved Baked Sweet Potato Fries (1lb)",
    yield: 24,
    baselineRate: 37,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Sweet Potato Fries',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Competition Approved Grilled Chicken W/ Smokin Poppie Sauce (1lb)",
    yield: 25,
    baselineRate: 65,
    stove: "",
    oven: "",
    grill: "Flavor Gang Chicken",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken"
  },
  {
    name: "Competition Approved Grilled Flank Steak (1lb)",
    yield: 28,
    baselineRate: 54,
    stove: "",
    oven: "",
    grill: "Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Competition Approved Lemon Pepper Salmon (1lb)",
    yield: 6,
    baselineRate: 20,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Salmon',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Competition Approved White Basmati Rice (1lb)",
    yield: 27,
    baselineRate: 22,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Basmati Rice',
    rawMeats: ""
  },
  {
    name: "Crispy Baked Chicken Wrap",
    yield: 85,
    baselineRate: 189,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Crispy Chicken',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Herb Butter Steak Tips Bowl",
    yield: 66,
    stove: "Mashed Potato",
    oven: "",
    grill: "",
    flatGrill: "Herb Butter Steak",
    saladStation: "Scallions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Cube Steak",
  },
  {
    name: "HFit Signature Fold",
    yield: 86,
    baselineRate: 122,
    stove: "",
    oven: "Fold Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Fold Mix",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken"
  },
  {
    name: "Keto Ricotta Meatballs",
    yield: 65,
    baselineRate: 85,
    stove: "Keto Ricotta Sauce",
    oven: "Keto Ricotta Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Ground Chicken"
  },
  {
    name: "Lo Mein Teriyaki Steak",
    yield: 75,
    baselineRate: 122,
    stove: "Lo Mein Pasta",
    oven: "",
    grill: "",
    flatGrill: "Lo Mein Steak",
    saladStation: "Scallions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Pesto Steak"
  },


  {
    name: "MsWendy Buff Nuggets",
    yield: 60,
    baselineRate: 108,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: 'Nuggets',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Pineapple Teriyaki Meatballs",
    yield: 81,
    baselineRate: 63,
    stove: "Jasmine Rice",
    oven: "Teri Yaki P. Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "Scallions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Ground Chicken"
  },
  {
    name: "Rigatoni & Meatballs",
    yield: 85,
    baselineRate: 111,
    stove: "Rigatoni Pasta & Sauce",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: ""
  },



  {
    name: "Teriyaki Flank Bowl",
    yield: 80,
    baselineRate: 139,
    stove: "",
    oven: "",
    grill: "Teriyaki Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Basmati Rice',
    rawMeats: ""
  },

  {
    name: "The Clean Bulk Pasta Bowl",
    yield: 32,
    baselineRate: 100,
    stove: "Penne, Clean Bulk Sauce",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Cut Parsley",
    sauceStation: "",
    mainKitchen: 'Ground Beef',
    holbrook: '',
    rawMeats: ""
  },
  {
    name: "Zeus Bowl",
    yield: 78,
    baselineRate: 177,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Zeus Sauce",
    mainKitchen: 'Chicken Kebab',
    holbrook: 'Basmati Rice',
    rawMeats: "Cube Chicken"
  },
  {
    name: "Vegan Chorizo Quesadilla",
    isVegan: true,
    yield: 45,
    stove: "",
    oven: "Vegan Chorizo, Vegan Beef",
    grill: "",
    flatGrill: "",
    saladStation: "Vegan Quesadillas Mix",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Closed on Sunday Crispy Chicken Bowl",
    yield: 70,
    baselineRate: 175,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "CFA Sauce",
    mainKitchen: 'Russet Potato Wedges, Crispy Chicken Bowl Tenders',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "The Arches Mac Daddy Wrap",
    yield: 70,
    baselineRate: 54,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "White Onion",
    sauceStation: "Arches Mac Daddy Sauce",
    mainKitchen: 'Ground Beef',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Texas Queso Steak Bowl",
    yield: 70,
    baselineRate: 80,
    stove: "Lime Rice",
    oven: "",
    grill: "",
    flatGrill: "Cube Seasoned Steak",
    saladStation: "Red Bean Corn Salad, Peppers and Onions",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Cube Steak",
  },
  {
    name: "Philly Cheesesteak Quesadilla",
    yield: 70,
    baselineRate: 80,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Philly Cheesesteak, Onion & Peppers",
    saladStation: "Peppers and Onions",
    sauceStation: "Philly Steak Sauce",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Honey Garlic Crispy Chicken Tacos",
    yield: 70,
    baselineRate: 0,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Cole Slaw Mix",
    sauceStation: "",
    mainKitchen: 'Popcorn Chicken',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Animal Style West Coast Beef Bowl",
    yield: 70,
    baselineRate: 0,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Caramelized Onion",
    saladStation: "Caramelized Onion",
    sauceStation: "Animal Style West Coast Sauce",
    mainKitchen: 'Russet Wedge Potatoes, Ground Beef',
    holbrook: '',
    rawMeats: "",
  },
  {
    name: "Zeus Bowl V2",
    yield: 87,
    baselineRate: 82,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Zeus Sauce",
    mainKitchen: 'Chicken Kebab, Cube Potatoes',
    holbrook: '',
    rawMeats: "Cube Chicken"
  },
  {
    name: "Chipotle Chicken (1lb Competition Approved)",
    yield: 25,
    baselineRate: 85,
    stove: "",
    oven: "",
    grill: "Chipotle Chicken",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: '',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Arnold 2022 Bowl",
    yield: 83,
    baselineRate: 114,
    stove: "",
    oven: "",
    grill: "Arnold Chicken, Grilled Asparagus",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Sticky Rice',
    rawMeats: "Filet Chicken",
  },
  {
    name: "Grilled Chicken Parmesan Wrap",
    yield: 70,
    baselineRate: 129,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    mainKitchen: '',
    holbrook: 'Chicken Parm Wrap',
    rawMeats: "Filet Chicken",
  },
];

module.exports = { GROUP1_MEALS, GROUP2_MEALS, DIRECT_TO_ASSEMBLY };
