// ============================================================
//  MEAL REFERENCE DATA — GOD MODE UPDATE (May 2026)
//  All Shopify product names verified + station assignments synced
//  with Gemini God Mode engine
// ============================================================

// Direct to Assembly items — bypass all hot line stations
// Print exact unit count instead of batches
const DIRECT_TO_ASSEMBLY = [
  "Meatball Parmesan Wrap",
  "Vegan Breakfast Sandwich"
];

const GROUP1_MEALS = [
  {
    name: "Arnold 2022 Bowl",
    yield: 83,
    stove: "Sticky Rice",
    oven: "",
    grill: "Arnold Chicken, Grilled Asparagus",
    flatGrill: "",
    saladStation: "Asparagus",
    sauceStation: "",
    rawMeats: "1/3 Filet Chicken",
  },
  {
    name: "Baja Chicken Tacos",
    yield: 75,
    stove: "Basmati Rice",
    oven: "",
    grill: "Baja Chicken",
    flatGrill: "",
    saladStation: "Cut Cilantro",
    sauceStation: "",
    rawMeats: "1/3 Chicken Breast",
  },
  {
    name: "Baked Herb Chicken & Potatoes",
    yield: 75,
    stove: "",
    oven: "Chicken, Green Beans, Potatoes",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "1/2 Filet Oven",
  },
  {
    name: "Baked Herbed Tilapia (1lb Competition Approved)",
    yield: 6,
    stove: "",
    oven: "Tilapia",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "BBQ Chicken Garlic Parm Potatoes",
    yield: 79,
    stove: "Sauce",
    oven: "Cube Potatoes",
    grill: "",
    flatGrill: "Garlic Parm Chicken",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Blueberry French Toast",
    yield: 65,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Blueberry Frenchie",
    saladStation: "",
    sauceStation: "Blueberry Sauce",
    rawMeats: "",
  },
  {
    name: "Brookfield Chicken Bowl",
    yield: 90,
    stove: "Cilantro Lime Rice",
    oven: "Sazon Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "1/2 Filet Oven",
  },
  {
    name: "Broritto Burrito",
    yield: 75,
    stove: "",
    oven: "",
    grill: "Chipotle Chicken",
    flatGrill: "",
    saladStation: "Burrito Salad",
    sauceStation: "",
    rawMeats: "1/3 Filet Chicken",
  },
  {
    name: "Buffalo Chicken Meatballs",
    yield: 120,
    stove: "",
    oven: "Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Buffalo Crispy Chicken Wrap",
    yield: 85,
    stove: "",
    oven: "Crispy Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Celery",
    sauceStation: "Buffalo Sauce",
    rawMeats: "",
  },
  {
    name: "Chicken Mushroom Pot Stickers",
    yield: 77,
    stove: "",
    oven: "Mushroom",
    grill: "",
    flatGrill: "",
    saladStation: "Sliced Mushrooms",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Chicken Taco Bowl",
    yield: 80,
    stove: "Brown Rice, Taco Pulled Chicken",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Red Bean Corn Salad",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Chipotle Chicken (1lb Competition Approved)",
    yield: 25,
    stove: "",
    oven: "",
    grill: "Chipotle Chicken",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "1/2 Filet Oven",
  },
  {
    name: "Cinnamon Roll Pancakes",
    yield: 60,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Cinnamon Roll Pancakes",
    saladStation: "",
    sauceStation: "Cinnamon Sauce",
    rawMeats: "",
  },
  {
    name: "Club Wrap",
    yield: 73,
    stove: "",
    oven: "Club Wrap Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Club Wrap Sauce",
    rawMeats: "Pesto Chicken",
  },
  {
    name: "Competition Approved Chicken Kebab (1lb)",
    yield: 28,
    stove: "",
    oven: "Chicken Kebab",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Cube Chicken",
  },
  {
    name: "Competition Approved Grilled Chicken (1lb)",
    yield: 25,
    stove: "",
    oven: "",
    grill: "Arnold",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "1/3 Filet",
  },
  {
    name: "Competition Approved Sticky Rice (1lb)",
    yield: 32,
    stove: "Sticky Rice",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Competition Approved Oven Baked Cod (1lb)",
    yield: 5,
    stove: "",
    oven: "Cod",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Crispy Vegan Wrap",
    yield: 53,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Vegan Beef",
  },
  {
    name: "Farfalle & Chicken Alfredo",
    yield: 85,
    stove: "Farfalle Pasta & Sauce",
    oven: "Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Scallions",
    sauceStation: "",
    rawMeats: "Half",
  },
  {
    name: "Fit Ala Vodka With Chicken",
    yield: 85,
    stove: "Penne Vodka Sauce",
    oven: "",
    grill: "Basil Chicken",
    flatGrill: "",
    saladStation: "Parsley",
    sauceStation: "",
    rawMeats: "1/3 Filet Chicken",
  },
  {
    name: "Fit-Fil-A",
    yield: 75,
    stove: "",
    oven: "Waffle Fries, Smoked Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "1/2 Oven Filet",
  },
  {
    name: "GLORIOUS GAINS Steak Bites & Cilantro Lime Rice",
    yield: 70,
    stove: "Cilantro Lime Rice",
    oven: "",
    grill: "",
    flatGrill: "Glorious Steak",
    saladStation: "",
    sauceStation: "Glorious Sauce",
    rawMeats: "Cube Steak",
  },
  {
    name: "Gluten Free Carbonara Chicken",
    yield: 79,
    stove: "Pasta & Sauce",
    oven: "",
    grill: "GF Carbonara Chicken",
    flatGrill: "",
    saladStation: "Parsley",
    sauceStation: "",
    rawMeats: "Fillet Chicken",
  },
  {
    name: "Grilled Chicken Parmesan Wrap",
    yield: 70,
    stove: "",
    oven: "",
    grill: "Basil Chicken",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "1/3 Filet Chicken",
  },
  {
    name: "Grilled Chicken Pesto Wrap",
    yield: 73,
    stove: "",
    oven: "Pesto Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Fresh Mozzarella",
    sauceStation: "Pesto Sauce",
    rawMeats: "Pesto Chicken",
  },
  {
    name: "Grillin' Gains",
    yield: 65,
    stove: "Grillin Gains Rice",
    oven: "",
    grill: "Chicken & Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Filet Grill",
  },
  {
    name: "Hey Arnold! Burrito",
    yield: 75,
    stove: "",
    oven: "",
    grill: "Hey Arnold Chicken",
    flatGrill: "",
    saladStation: "Hey Arnold Salad",
    sauceStation: "",
    rawMeats: "Fillet Chicken",
  },
  {
    name: "Hot Honey Steak & Mac",
    yield: 68,
    stove: "Rotini Pasta",
    oven: "",
    grill: "Hot Honey Steak",
    flatGrill: "",
    saladStation: "Mix Rotini Pasta",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Meatball Parmesan Wrap",
    yield: 30,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Nacho Average Bowl",
    yield: 71,
    stove: "Ground Beef",
    oven: "Sweet Potato Fries",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Nacho Average Vegan Bowl",
    yield: 32,
    stove: "",
    oven: "Vegan Beef, Sweet Fries",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Soho Steak Bowl",
    yield: 90,
    stove: "",
    oven: "Sweet Potato Fries",
    grill: "Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Southwest Chicken Bowl",
    yield: 75,
    stove: "Basmati Rice",
    oven: "SW Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Corn Salad",
    sauceStation: "",
    rawMeats: "1/2 Filet Oven",
  },
  {
    name: "Southwest Chicken Quesadilla",
    yield: 80,
    stove: "Pulled Chicken",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Quesadilla Veggies",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Spicy Buffalo Wrap",
    yield: 73,
    stove: "",
    oven: "Chicken Kebab",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Cube Chicken",
  },
  {
    name: "Stacked and Jacked",
    yield: 103,
    stove: "",
    oven: "Potato Fries",
    grill: "",
    flatGrill: "Burger Patty",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Strawberry Protein French Toast",
    yield: 65,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Strawberry Frenchie",
    saladStation: "",
    sauceStation: "Sauce",
    rawMeats: "",
  },
  {
    name: "Thai Chili Chicken",
    yield: 72,
    stove: "Sticky Rice",
    oven: "",
    grill: "",
    flatGrill: "Thai Chili Chicken",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Cube Chicken",
  },
  {
    name: "Turkey Bacon Cheddar Egg Muffins",
    yield: 44,
    stove: "",
    oven: "Egg Muffin",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Vegan Breakfast Sandwich",
    yield: 1,
    directToAssembly: true,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Vegan Cheeseburger Bowl",
    yield: 70,
    stove: "Basmati Rice",
    oven: "Vegan Chorizo",
    grill: "",
    flatGrill: "",
    saladStation: "Onion/Pickle",
    sauceStation: "",
    rawMeats: "",
  },
];

const GROUP2_MEALS = [
  {
    name: "6-Guys Patty Melt",
    yield: 102,
    stove: "",
    oven: "Sweet Potato Fries",
    grill: "",
    flatGrill: "Burger Patty",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Ground Beef"
  },
  {
    name: "BBQ Chicken Mac Bowl",
    yield: 80,
    stove: "Rotini Pasta",
    oven: "",
    grill: "",
    flatGrill: "Barbecue Chicken",
    saladStation: "Cut Parsley, Scallions",
    sauceStation: "",
    rawMeats: "Cube Chicken"
  },
  {
    name: "Breakfast Burrito",
    yield: 75,
    stove: "",
    oven: "Cube Potatoes",
    grill: "",
    flatGrill: "Yellow Eggs",
    saladStation: "Cut Veggies",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Buffalo Chicken Quesadilla",
    yield: 87,
    stove: "Taco Pulled Chicken",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Buffalo Mac N Chicken",
    yield: 90,
    stove: "Elbow Pasta Mix",
    oven: "Chicken Kebabs",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Cube Chicken"
  },
  {
    name: "Cheeseburger Bowl",
    yield: 93,
    stove: "Basmati, Gr. Beef",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Onion/Pickle",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Cheesy Garlic Chicken Wrap",
    yield: 74,
    stove: "Garlic Sauce",
    oven: "",
    grill: "",
    flatGrill: "Cheesy Garlic Chicken",
    saladStation: "Chicken Wrap Mix",
    sauceStation: "Cheesy Garlic Sauce",
    rawMeats: "Cube Chicken"
  },
  {
    name: "Chicken Stir Fry",
    yield: 80,
    stove: "Peas/Carrots Rice",
    oven: "",
    grill: "",
    flatGrill: "Stir Fry Chicken",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Competition Approved 90/10 Lean Ground Beef (1lb)",
    yield: 22,
    stove: "Ground Beef",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Competition Approved Baked Sweet Potato Fries (1lb)",
    yield: 24,
    stove: "",
    oven: "Sweet Potato Fries",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Competition Approved Grilled Chicken W/ Smokin Poppie Sauce (1lb)",
    yield: 25,
    stove: "",
    oven: "",
    grill: "Flavor Gang Chicken",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Fillet Chicken"
  },
  {
    name: "Competition Approved Grilled Flank Steak (1lb)",
    yield: 28,
    stove: "",
    oven: "",
    grill: "Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Competition Approved Lemon Pepper Salmon (1lb)",
    yield: 6,
    stove: "",
    oven: "Salmon",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Competition Approved White Basmati Rice (1lb)",
    yield: 27,
    stove: "Basmati Rice",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Crispy Baked Chicken Wrap",
    yield: 85,
    stove: "",
    oven: "Crispy Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: "",
  },
  {
    name: "Garden Orzo & Meatballs",
    yield: 76,
    stove: "Orzo Rice",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Garlic Flank & Potatoes",
    yield: 75,
    stove: "",
    oven: "Colored Potatoes",
    grill: "",
    flatGrill: "Garlic Steak",
    saladStation: "",
    sauceStation: "",
    rawMeats: "Pesto Steak"
  },
  {
    name: "General Tso Tacos",
    yield: 68,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Tso Chicken",
    saladStation: "White Cabbage",
    sauceStation: "",
    rawMeats: "Triple Cube Chicken"
  },
  {
    name: "Harrison Chicken Pasta Bowl",
    yield: 110,
    stove: "Penne Pasta, Marinara",
    oven: "Breaded Cutlet",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Herb Butter Steak Tips Bowl",
    yield: 66,
    stove: "Mashed Potato",
    oven: "",
    grill: "",
    flatGrill: "Herb Butter Steak",
    saladStation: "Scallions",
    sauceStation: "",
    rawMeats: "Cube Steak",
  },
  {
    name: "HFit Signature Fold",
    yield: 86,
    stove: "",
    oven: "Fold Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Fold Mix",
    sauceStation: "",
    rawMeats: "1/2 Filet Oven"
  },
  {
    name: "Keto Ricotta Meatballs",
    yield: 65,
    stove: "Keto Ricotta Sauce",
    oven: "Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Lo Mein Teriyaki Steak",
    yield: 75,
    stove: "Lo Mein Pasta",
    oven: "",
    grill: "Teriyaki Steak",
    flatGrill: "",
    saladStation: "Scallions",
    sauceStation: "",
    rawMeats: "Pesto Steak"
  },
  {
    name: "Low Carb Keto Cheeseburger Bowl",
    yield: 80,
    stove: "Ground Beef",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Onion/Pickle",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "MickieStrips",
    yield: 88,
    stove: "",
    oven: "Waffle Fries, Tenders",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Mickie Strips Sauce",
    rawMeats: ""
  },
  {
    name: "MsWendy Buff Nuggets",
    yield: 60,
    stove: "",
    oven: "Nuggets",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Pineapple Teriyaki Meatballs",
    yield: 81,
    stove: "Jasmine Rice",
    oven: "Teri Yaki P. Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "Scallions",
    sauceStation: "",
    rawMeats: "Ground Chicken"
  },
  {
    name: "Rigatoni & Meatballs",
    yield: 85,
    stove: "Rigatoni Sauce",
    oven: "Chicken Meatballs",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Strongsville Chicken Ranch Fold",
    yield: 88,
    stove: "",
    oven: "Ranch Chicken",
    grill: "",
    flatGrill: "",
    saladStation: "Mix Ranch Fold",
    sauceStation: "",
    rawMeats: "1/2 Filet Oven"
  },
  {
    name: "Sunrise Breakfast",
    yield: 78,
    stove: "",
    oven: "Cube Potatoes",
    grill: "",
    flatGrill: "Yellow Eggs w/ Cheese",
    saladStation: "",
    sauceStation: "BBQ Sriracha",
    rawMeats: ""
  },
  {
    name: "Surf N Turf Shrimp & Steak",
    yield: 72,
    stove: "",
    oven: "Potato Halves",
    grill: "Shrimp/Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Pesto Sauce",
    rawMeats: ""
  },
  {
    name: "Taco Build Quesadilla",
    yield: 104,
    stove: "",
    oven: "",
    grill: "",
    flatGrill: "Taco Build Chicken",
    saladStation: "Mix Taco Build Quesadilla",
    sauceStation: "",
    rawMeats: "Triple Cut Cube"
  },
  {
    name: "Taco Poblano Bowl",
    yield: 80,
    stove: "Basmati, Gr. Beef",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Red Onion",
    sauceStation: "",
    rawMeats: "Cube Chicken"
  },
  {
    name: "Teriyaki Flank Bowl",
    yield: 80,
    stove: "Basmati Rice",
    oven: "",
    grill: "Steak",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "TexMex Potato Hash",
    yield: 84,
    stove: "Ground Beef",
    oven: "Cube Seasoned Potatoes",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "The Clean Bulk Pasta Bowl",
    yield: 32,
    stove: "Penne, Gr. Beef",
    oven: "",
    grill: "",
    flatGrill: "",
    saladStation: "Mix Clean Bulk, Cut Parsley",
    sauceStation: "",
    rawMeats: ""
  },
  {
    name: "Zeus Bowl",
    yield: 78,
    stove: "Basmati Rice",
    oven: "Chicken Kebab",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Zeus Sauce",
    rawMeats: "Cube Chicken"
  },
  {
    name: "Vegan Chorizo Quesadilla",
    yield: 51,
    stove: "",
    oven: "Vegan Chorizo",
    grill: "",
    flatGrill: "",
    saladStation: "Vegan Quesadillas Mix",
    sauceStation: "",
    rawMeats: "Vegan Beef",
  },
  {
    name: "Zeus Bowl V2",
    yield: 87,
    stove: "",
    oven: "Chicken Kebab, Cube Potatoes",
    grill: "",
    flatGrill: "",
    saladStation: "",
    sauceStation: "Zeus Sauce",
    rawMeats: "Cube Chicken"
  }
];

module.exports = { GROUP1_MEALS, GROUP2_MEALS, DIRECT_TO_ASSEMBLY };
